### ISSUE TITLE
Magento 2.4.1 and PHP 7.4

### ISSUE THREAD

**Issue by jorgb90** [naseemqota/CustomerOrderSearch#2]
Hi,

Can you update the extension to be compatible with Magento 2.4.1 and PHP 7.4?

Thanks!

**Comment by naseemqota** [comment]
Sure ill do that. With in this week.

**Comment by jorgb90** [comment]
Thanks @naseemqota

**Comment by jorgb90** [comment]
Just a friendly reminder :)

**Comment by naseemqota** [comment]
On Monday you will get a better version of it.

**Comment by jorgb90** [comment]
Nice! Thanks again!

**Comment by jorgb90** [comment]
I cant wait :)

**Comment by jorgb90** [comment]
I hardly dare to ask, but do you have any update for me?

**Comment by jorgb90** [comment]
Still plans to do this? Or should I forget it?

**Comment by dmcmillin** [comment]
has anyone managed to do this or has this turned into a zombie project?

**Comment by naseemqota** [comment]
i'll work on it #naseemqota

**Comment by naseemqota** [comment]
composer require qota/customer-order-search

please start using this @dmcmillin @jorgb90
